import os

EMAIL_HOST = os.getenv('EMAIL_HOST')
SOURCE_EMAIL = os.getenv('SOURCE_EMAIL')
EMAIL_PASSWD = os.getenv('EMAIL_PASSWD')
EMAIL_PORT_SSL = os.getenv('EMAIL_PORT_SSL')
TARGET_EMAIL = os.getenv('TARGET_EMAIL')

EMAIL_SUBJECT = os.getenv('EMAIL_SUBJECT')
EMAIL_MESSAGE = os.getenv('EMAIL_MESSAGE')
